// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250415114147_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Backend.Models.Chantier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chantiers");
                });

            modelBuilder.Entity("Backend.Models.Communication.Annonce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChantierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChantierId");

                    b.ToTable("Annonces");
                });

            modelBuilder.Entity("Backend.Models.Management.Mouvement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChantierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("TEXT");

                    b.Property<int>("RessourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChantierId");

                    b.HasIndex("RessourceId");

                    b.ToTable("Mouvements");
                });

            modelBuilder.Entity("Backend.Models.Management.Rapport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChantierId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Fichier")
                        .HasColumnType("BLOB");

                    b.Property<int>("Mois")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChantierId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("Backend.Models.Management.Ressource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChantierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChantierId");

                    b.ToTable("Ressources");
                });

            modelBuilder.Entity("Backend.Models.Planning.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChantierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChantierId");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("Backend.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleUtilisateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ChantierUtilisateur", b =>
                {
                    b.Property<int>("ChantiersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChantiersId", "MembresId");

                    b.HasIndex("MembresId");

                    b.ToTable("ChantierMembre", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Communication.Annonce", b =>
                {
                    b.HasOne("Backend.Models.Chantier", "Chantier")
                        .WithMany("Annonces")
                        .HasForeignKey("ChantierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");
                });

            modelBuilder.Entity("Backend.Models.Management.Mouvement", b =>
                {
                    b.HasOne("Backend.Models.Chantier", "Chantier")
                        .WithMany("Mouvements")
                        .HasForeignKey("ChantierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Management.Ressource", "Ressource")
                        .WithMany()
                        .HasForeignKey("RessourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");

                    b.Navigation("Ressource");
                });

            modelBuilder.Entity("Backend.Models.Management.Rapport", b =>
                {
                    b.HasOne("Backend.Models.Chantier", "Chantier")
                        .WithMany("Rapports")
                        .HasForeignKey("ChantierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");
                });

            modelBuilder.Entity("Backend.Models.Management.Ressource", b =>
                {
                    b.HasOne("Backend.Models.Chantier", "Chantier")
                        .WithMany("Ressources")
                        .HasForeignKey("ChantierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");
                });

            modelBuilder.Entity("Backend.Models.Planning.Tache", b =>
                {
                    b.HasOne("Backend.Models.Chantier", "Chantier")
                        .WithMany("Taches")
                        .HasForeignKey("ChantierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chantier");
                });

            modelBuilder.Entity("ChantierUtilisateur", b =>
                {
                    b.HasOne("Backend.Models.Chantier", null)
                        .WithMany()
                        .HasForeignKey("ChantiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("MembresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Chantier", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("Mouvements");

                    b.Navigation("Rapports");

                    b.Navigation("Ressources");

                    b.Navigation("Taches");
                });
#pragma warning restore 612, 618
        }
    }
}
